server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # This line is crucial for React Router to work in Docker
        try_files $uri $uri/ /index.html; 
    }
}